# Storage definition for Zookeeper.
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zookeeper-data-claim
spec:
  accessModes: [ "ReadWriteOnce" ]
  resources:
    requests:
      storage: 10Gi
  storageClassName: linode-block-storage