name: Akamai Datastream 2 Kafka Connector Pipeline

on:
  push:
    branches: [ "*" ]
    paths-ignore:
      - "*.md"
      - "about.txt"
      - "banner.txt"
      - "deploy.sh"
      - "fluentd/etc/*"
      - "iac/*.tf"
      - "iac/*.sh"
      - "kafka-broker/bin/*"
      - "kafka-broker/etc/*"
      - "LICENSE"
      - "nginx/etc/*"
      - "undeploy.sh"

permissions:
  contents: read

jobs:
  build:
    name: Jobs
    runs-on: ubuntu-latest

    steps:
      - name: Download the project files.
        uses: actions/checkout@v3

      - name: Package services.
        run: ./package.sh

      - name: Publish services.
        env:
          DOCKER_REGISTRY_PASSWORD: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
        run: ./publish.sh